services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: mc-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"     # SERVER TYPE (PAPER, SPIGOT, VANILLA)
      VERSION: "26.1.2" # MC VERSION
      MEMORY: "5G"      # MEMORY ALLOCATED TO MC
    volumes:
      - ./mc-data:/data
      - ./config/server.properties:/data/server.properties
    ports:
      - "25565:25565"
    restart: unless-stopped

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - prometheus_data:/prometheus
  #   command:
  #     - --config.file=/etc/prometheus/prometheus.yml
  #     - --storage.tsdb.path=/prometheus
  #     - --storage.tsdb.retention.time=5d   #how long to keep metrics data (5days)
  #   restart: unless-stopped

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - --path.procfs=/host/proc
  #     - --path.sysfs=/host/sys
  #     - --path.rootfs=/rootfs

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   restart: unless-stopped
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning:ro  # for loading dashboards and datasources
  #   restart: unless-stopped

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: grafana-proxy
  #   depends_on:
  #     - grafana
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   restart: unless-stopped

  # mc-stats-exporter:
  #   build:
  #     context: ./mc-stats-exporter
  #   container_name: mc-stats-exporter
  #   environment:
  #     DATA_DIR: "/data"
  #     PORT: "9225"
  #     MC_QUERY_HOST: "minecraft"
  #     MC_QUERY_PORT: "25565"
  #     QUERY_TIMEOUT: "1.0"
  #   volumes:
  #     - ./mc-data:/data:ro
  #   restart: unless-stopped


#TODO
 #    !!!!!!!!jak latwo sprawdzac logiii  !!!!!!!!jak latwo sprawdzac logiii 
 #+ pobieranie mapy co jakis czas
 #zeby byly na stale dashboardy node + docker stats

volumes:
  prometheus_data:
  grafana_data:
